# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Eric Osterberg and OpenSalesTax contributors
"""Regenerate src/opensalestax/data/zip_county.py.

Pulls the Census Bureau ZCTA->County 2020 relationship file and emits
a ZIP -> set-of-(state_abbrev, county_fips) lookup. Most ZIPs map to
a single county, but a meaningful minority straddle county lines
(Census records each intersection separately).

The lookup is the authoritative source the FL/AZ/CA loaders use to
emit county-level boundary rows for every ZIP in the state, not just
the ZIPs in their hand-curated city seed lists. Without it, ZIPs in
covered counties but outside the city list keep only the state-level
binding from the Census ZCTA load and under-collect the county portion
(e.g., Miami Beach 33139 returning state-only 6% instead of the
correct 7% with Miami-Dade's 1% surtax).

Usage:

    poetry run python scripts/regen_zip_county.py

The Census file (~3 MB, public domain) is fetched once and cached at
``$OPENSALESTAX_DATA_DIR/tab20_zcta520_county20_natl.txt`` (defaults to
``~/.opensalestax/data/``). Re-run this script to refresh after a
2030 decennial relationship file is published.
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from opensalestax.data.state_fips import FIPS_TO_ABBREV  # noqa: E402

CENSUS_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/"
    "tab20_zcta520_county20_natl.txt"
)
TARGET = ROOT / "src" / "opensalestax" / "data" / "zip_county.py"


def fetch_source() -> str:
    print(f"fetching {CENSUS_URL} ...")
    with urlopen(CENSUS_URL, timeout=60) as resp:  # noqa: S310 - URL is hard-coded
        return resp.read().decode("utf-8-sig")


def main() -> None:
    text = fetch_source()
    triples: set[tuple[str, str, str]] = set()
    for line in text.splitlines():
        parts = line.strip().split("|")
        if len(parts) < 11:
            continue
        zip5 = parts[1].strip()
        county_geoid = parts[9].strip()
        if not zip5 or not county_geoid or len(county_geoid) != 5:
            continue
        if not county_geoid.isdigit():
            continue
        state_fips = county_geoid[:2]
        county_fips = county_geoid[2:]
        abbrev = FIPS_TO_ABBREV.get(state_fips)
        if not abbrev:
            continue
        triples.add((zip5, abbrev, county_fips))

    by_zip: dict[str, set[tuple[str, str]]] = {}
    for zip5, abbrev, county_fips in triples:
        by_zip.setdefault(zip5, set()).add((abbrev, county_fips))

    out = [
        "# SPDX-License-Identifier: Apache-2.0",
        "# Copyright 2026 Eric Osterberg and OpenSalesTax contributors",
        '"""Authoritative ZIP -> (state, county FIPS) mapping (Census ZCTA 2020).',
        "",
        "Generated by scripts/regen_zip_county.py from the Census Bureau",
        "ZCTA->County 2020 relationship file (public domain). Most ZIPs",
        "map to a single county; a meaningful minority straddle county",
        "lines (those map to a frozenset of multiple (state, county_fips)",
        "tuples).",
        "",
        "Used by FL/AZ/CA state modules to emit county-level boundary",
        "rows for every ZIP in the state, not just the ZIPs in the hand-",
        "curated city seed list. Without this lookup, ZIPs outside the",
        "top-N city list under-collect the county portion (e.g., Miami",
        "Beach 33139 returning state-only 6% instead of the correct 7%",
        "with Miami-Dade's 1% surtax).",
        "",
        "Each value is a frozenset of (state_abbrev, 3-digit county FIPS)",
        "tuples. The 3-digit FIPS matches the keys in",
        ":data:`opensalestax.data.county_names.COUNTY_NAMES`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# Key: 5-digit ZIP code as string",
        "# Value: frozenset of (state_abbrev, 3-digit county FIPS) tuples",
        "# the ZIP intersects per Census ZCTA->county boundaries.",
        "ZIP_COUNTY: dict[str, frozenset[tuple[str, str]]] = {",
    ]
    for zip5 in sorted(by_zip):
        pairs = sorted(by_zip[zip5])
        rendered = ", ".join(f'("{s}", "{c}")' for s, c in pairs)
        out.append(f'    "{zip5}": frozenset({{{rendered}}}),')
    out.extend([
        "}",
        "",
        "",
        "def counties_for_zip(zip5: str, state_abbrev: str) -> frozenset[str]:",
        '    """Return the set of 3-digit county FIPS codes that ``zip5`` intersects',
        "    within ``state_abbrev``, or an empty frozenset if the ZIP isn't in the",
        "    table for that state.",
        "",
        "    A ZIP that crosses state lines may belong to multiple states; this",
        "    helper filters to the requested state so a state module can iterate",
        "    only the counties relevant to its own jurisdiction.",
        '    """',
        "    pairs = ZIP_COUNTY.get(zip5)",
        "    if pairs is None:",
        "        return frozenset()",
        "    state = state_abbrev.upper()",
        "    return frozenset(c for s, c in pairs if s == state)",
        "",
        "",
        '__all__ = ["ZIP_COUNTY", "counties_for_zip"]',
        "",
    ])

    TARGET.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {len(by_zip)} ZIP entries to {TARGET}")


if __name__ == "__main__":
    main()
