# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Eric Osterberg and OpenSalesTax contributors
"""Regenerate src/opensalestax/data/county_names.py.

One-shot helper that pulls the Census Bureau ZCTA->County 2020
relationship file (~3 MB, public domain) and emits the
COUNTY_NAMES dict keyed by (state_abbrev, 3-digit county FIPS).

Re-run when the Census publishes a 2030 (or later) file with
renamed / added counties, or when the state FIPS table grows.

Usage:

    poetry run python scripts/regen_county_names.py

The output is checked into git so the engine doesn't need
network access at runtime.
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from opensalestax.data.state_fips import FIPS_TO_ABBREV  # noqa: E402

CENSUS_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/"
    "tab20_zcta520_county20_natl.txt"
)
TARGET = ROOT / "src" / "opensalestax" / "data" / "county_names.py"


def fetch_source() -> str:
    print(f"fetching {CENSUS_URL} ...")
    with urlopen(CENSUS_URL, timeout=60) as resp:  # noqa: S310 - URL is hard-coded, not user input
        return resp.read().decode("utf-8-sig")


def main() -> None:
    text = fetch_source()
    rows: list[tuple[str, str, str]] = []
    for line in text.splitlines():
        parts = line.strip().split("|")
        # The Census file has 18 columns; we need col1 (GEOID_ZCTA5_20)
        # and col10 (GEOID_COUNTY_20) and col11 (NAMELSAD_COUNTY_20).
        if len(parts) < 11:
            continue
        county_geoid = parts[9].strip()
        county_name_value = parts[10].strip()
        if not county_geoid or not county_name_value:
            continue
        if len(county_geoid) != 5 or not county_geoid.isdigit():
            continue
        state_fips = county_geoid[:2]
        county_fips = county_geoid[2:]
        abbrev = FIPS_TO_ABBREV.get(state_fips)
        if not abbrev:
            continue
        rows.append((abbrev, county_fips, county_name_value))

    rows = sorted(set(rows))

    out = [
        "# SPDX-License-Identifier: Apache-2.0",
        "# Copyright 2026 Eric Osterberg and OpenSalesTax contributors",
        '"""County / parish / borough name lookup keyed by (state, county FIPS).',
        "",
        "Generated by scripts/regen_county_names.py from the Census Bureau",
        "ZCTA->County 2020 relationship file (public domain). Covers all",
        "3,000+ US county-equivalents (50 states + DC + PR + USVI + Guam +",
        "American Samoa + Northern Mariana Islands).",
        "",
        "Used by SST state modules to translate the SST file's 3-digit",
        "county FIPS code into a friendly name like 'Hennepin County' or",
        "'Orleans Parish' for the engine's per-jurisdiction breakdown",
        "response. The name includes the canonical local suffix that",
        "appears on receipts.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# Key: (state_abbrev, 3-digit county FIPS code as string)",
        "# Value: friendly name including the local suffix",
        "COUNTY_NAMES: dict[tuple[str, str], str] = {",
    ]
    for abbrev, county_fips, name in rows:
        safe = name.replace('"', r"\"")
        out.append(f'    ("{abbrev}", "{county_fips}"): "{safe}",')
    out.extend([
        "}",
        "",
        "",
        "def county_name(state_abbrev: str, county_fips_3digit: str) -> str | None:",
        '    """Return the friendly county name for a (state, county) pair, or None."""',
        "    return COUNTY_NAMES.get((state_abbrev.upper(), county_fips_3digit))",
        "",
        "",
        '__all__ = ["COUNTY_NAMES", "county_name"]',
        "",
    ])

    TARGET.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {len(rows)} county entries to {TARGET}")


if __name__ == "__main__":
    main()
