# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Eric Osterberg and OpenSalesTax contributors
"""Regenerate src/opensalestax/data/zip_state.py.

Pulls the Census Bureau ZCTA->County 2020 relationship file and
emits a ZIP -> set-of-state-abbrevs lookup. Most ZIPs map to a
single state, but a handful straddle state lines (Census records
multiple counties per ZIP for these). The lookup is the
authoritative source the SST loader uses to drop cross-border
records like SD's quarterly file claiming ZIP 55401 (Minneapolis)
binds to South Dakota authorities.

Usage:

    poetry run python scripts/regen_zip_state.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from opensalestax.data.state_fips import FIPS_TO_ABBREV  # noqa: E402

CENSUS_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/"
    "tab20_zcta520_county20_natl.txt"
)
TARGET = ROOT / "src" / "opensalestax" / "data" / "zip_state.py"


def fetch_source() -> str:
    print(f"fetching {CENSUS_URL} ...")
    with urlopen(CENSUS_URL, timeout=60) as resp:  # noqa: S310 - URL is hard-coded
        return resp.read().decode("utf-8-sig")


def main() -> None:
    text = fetch_source()
    pairs: set[tuple[str, str]] = set()
    for line in text.splitlines():
        parts = line.strip().split("|")
        if len(parts) < 11:
            continue
        zip5 = parts[1].strip()
        county_geoid = parts[9].strip()
        if not zip5 or not county_geoid or len(county_geoid) != 5:
            continue
        if not county_geoid.isdigit():
            continue
        state_fips = county_geoid[:2]
        abbrev = FIPS_TO_ABBREV.get(state_fips)
        if not abbrev:
            continue
        pairs.add((zip5, abbrev))

    by_zip: dict[str, set[str]] = {}
    for zip5, abbrev in pairs:
        by_zip.setdefault(zip5, set()).add(abbrev)

    out = [
        "# SPDX-License-Identifier: Apache-2.0",
        "# Copyright 2026 Eric Osterberg and OpenSalesTax contributors",
        '"""Authoritative ZIP -> state mapping (Census ZCTA 2020).',
        "",
        "Generated by scripts/regen_zip_state.py from the Census Bureau",
        "ZCTA->County 2020 relationship file (public domain). Most ZIPs",
        "map to a single state; a small handful straddle state lines",
        "(those map to a frozenset of multiple states).",
        "",
        "Used by SST state modules to drop cross-border boundary records",
        "before they pollute the engine's lookup table -- e.g. South",
        "Dakota's published quarterly carries a Z-record covering ZIP",
        "range 51001-56136 (state_fips=46) which would otherwise bind",
        "Minneapolis (55401), Iowa, Nebraska, and Wisconsin ZIPs to SD",
        "tax authorities.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# Key: 5-digit ZIP code as string",
        "# Value: frozenset of USPS state abbrevs the ZIP physically",
        "# belongs to (per Census ZCTA->county boundaries).",
        "ZIP_STATES: dict[str, frozenset[str]] = {",
    ]
    for zip5 in sorted(by_zip):
        states = sorted(by_zip[zip5])
        out.append(f'    "{zip5}": frozenset({{{", ".join(repr(s) for s in states)}}}),')
    out.extend([
        "}",
        "",
        "",
        "def zip_in_state(zip5: str, state_abbrev: str) -> bool | None:",
        '    """Return True if ``zip5`` is physically in ``state_abbrev`` per Census,',
        "    False if it isn't, or None if the ZIP isn't in the table.",
        "",
        "    A None return means the ZIP isn't a Census ZCTA (often a PO-box-",
        "    only or business-only ZIP); callers should treat None as 'unknown",
        "    -- don't filter'.",
        '    """',
        "    states = ZIP_STATES.get(zip5)",
        "    if states is None:",
        "        return None",
        "    return state_abbrev.upper() in states",
        "",
        "",
        '__all__ = ["ZIP_STATES", "zip_in_state"]',
        "",
    ])

    TARGET.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {len(by_zip)} ZIP entries to {TARGET}")


if __name__ == "__main__":
    main()
